#spring配置
spring:
  data:
    redis:
      ##redis 单机环境配置
      host: ${BLADE_REDIS_HOST}
      port: ${BLADE_REDIS_PORT:6379}
      password: ${BLADE_REDIS_PASSWORD}
      database: ${BLADE_REDIS_DATABASE:0}
      ssl:
        enabled: false
      ##redis 集群环境配置
      #cluster:
      #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
      #  commandTimeout: 5000

#项目模块集中配置
blade:
  #通用开发生产环境数据库地址(特殊情况可在对应的子工程里配置覆盖)
  datasource:
    prod:
      url: ${BLADE_DATASOURCE_URL}
      username: ${BLADE_DATASOURCE_USERNAME}
      password: ${BLADE_DATASOURCE_PASSWORD}
